build/boxes/ElasticKube/events/install
src/api/server.py
src/api/v1/__init__.py

Do not start server if you cannot connect to Kube API or Mongo
Add missing dependencies for running the tests
@paulino-corujo @albertoarias

Wait settings are initialized before starting

---

src/ui/app/admin/ek-namespace-actions/ek-namespace-actions.directive.js

fix error when closing namespace actions dropdown

---

build/deploy.sh

Grep LoadBalancer IP if available in deploy.sh

---

build/deploy.sh

Detect if LoadBalancer ingress is configured in deploy.sh

---

src/api/v1/actions/invitations.py
src/api/v1/actions/namespaces.py
src/api/v1/auth.py

Add user to namespaces when validating invitation

---

src/api/kube/client.py

In case a message is sent over multiple chunks, we need to buffer it
to deserialize it properly
@paulino-corujo @albertoarias

Buffer message in kube client watch method

---

src/api/kube/pods.py
src/api/v1/actions/logs.py
src/api/v1/main.py
src/api/v1/watchers/kube.py

Fix retrieve method in LogsActions

---

src/ui/app/instances/ek-instance-list/ek-instance-list.less

justify right for actions in instance table

---

src/ui/app/core/directives/focus.js
src/ui/app/widgets/module.js

Add focus for label input when selecting a chart

---

src/ui/app/charts/ek-chart-card/ek-chart-card.controller.js
src/ui/app/charts/ek-chart-card/ek-chart-card.html
src/ui/app/charts/ek-chart-card/ek-chart-card.less

Add character limit to chart maintainers

---

src/ui/app/core/dataflow/log-store.service.js

Fix log buffer deletion error when the store is empty

---

src/ui/app/widgets/ek-table/ek-table.controller.js
src/ui/app/widgets/ek-table/ek-table.html
src/ui/app/widgets/ek-table/ek-table.less

Add padding for tables with no groups

---

src/ui/app/widgets/ek-table/ek-table.html
src/ui/app/widgets/ek-table/ek-table.less

Add special padding for group column in tables

---

build/boxes/Kubernetes/files/apiserver.jinja
build/kubegrunt/heapster/grafana-service.yaml
build/kubegrunt/heapster/heapster-controller.yaml
build/kubegrunt/heapster/heapster-service.yaml
build/kubegrunt/heapster/influxdb-grafana-controller.yaml
build/kubegrunt/heapster/influxdb-service.yaml

Update RC for Heapster to use 1.0.0 release

---

src/api/resources/invite.html
src/api/v1/actions/emails.py
src/api/v1/actions/invitations.py

Add reference to the user that sends the invitation in the email sent
@osanjuan @DiegoSanjuan @arnaud-elasticbox

Add inviter email and name to invite email

---

src/api/v1/auth.py
src/ui/app/core/dataflow/users-store.service.js

Fix user info encoding in signup

---

src/ui/app/instances/ek-instance-container-block/ek-instance-container-block.html
src/ui/app/instances/ek-instance-container-chart/ek-instance-container-chart.directive.js
src/ui/app/instances/ek-instance-container-chart/ek-instance-container-chart.html
src/ui/app/instances/ek-instance-container-chart/ek-instance-container-chart.less
src/ui/app/instances/ek-instance-overview-containers/ek-instance-overview-containers.html

Remove duplicate container name in chart legend in container view

---

src/ui/app/core/styles/input.less
src/ui/app/instances/ek-instance-bulk-actions/ek-instance-bulk-actions.less
src/ui/app/instances/ek-instance-container-block/ek-instance-container-block.less
src/ui/app/instances/ek-instance-container-log/ek-instance-container-log.less
src/ui/app/widgets/ek-container-state/ek-container-state.less

- added active state to bulk action button
- fixed input focus states
- removed inherited text transform from container title
- added border radius to container logs
@manolakis

added bulk action active state, fixed input focus states

---

src/api/v1/actions/invitations.py
src/diagnostics/diagnostics.py
src/diagnostics/templates/diagnostics.html
src/tests/requirements.txt

@albertoarias @davisein 
The tests are not passing but it is unrelated to this commit so it should be addressed separately.

Fix Heapster endpoint check in diagnostics

---

src/ui/app/charts/ek-chart-card/ek-chart-card.controller.js

Fix UI when there is not chart maintainer defined

---

src/ui/app/admin/ek-admin-menu/ek-admin-menu.controller.js
src/ui/app/admin/ek-admin-menu/ek-admin-menu.directive.js
src/ui/app/admin/ek-admin-menu/ek-admin-menu.html
src/ui/app/admin/ek-admin-menu/ek-admin-menu.less
src/ui/app/admin/icons.js

Add the link in the admin sidebar (on the left, the last item).
@mattnickles Take a look
@paulino-corujo

Add link to the diagnostics page in the admin section

---

src/ui/app/instances/instances-routes.js

Fix pod detail info lost when navigating from Replication Controller

---

build/kubegrunt/heapster/heapster-controller.yaml
build/vagrant/Vagrantfile
src/api/heapster/__init__.py
src/api/heapster/client.py
src/api/heapster/metrics.py
src/api/kube/client.py
src/api/kube/pods.py
src/api/schemas/metric.json
src/api/v1/__init__.py
src/api/v1/main.py
src/api/v1/sync/__init__.py
src/api/v1/sync/metrics.py
src/api/v1/sync/namespaces.py
src/api/v1/watchers/cursor.py
src/api/v1/watchers/kube.py
src/api/v1/watchers/metadata.py
src/api/v1/watchers/metrics.py
src/tests/api/watchers/watch_metrics_test.py
src/tests/requirements.txt

Separate Heapster client from Kube client
Use Heapster v.1.0.2 API
@albertoarias

Refactor Heapster API calls

---

build/boxes/Kubernetes/box.yaml

Upgrade Kubernetes version to 1.2.4

---

src/diagnostics/templates/diagnostics.html

centered checklist items with flexbox, removed padding, corrected color values
@manolakis @davisein

fixing alignment of diagnostic checklist items

---

src/ui/app/widgets/ek-insert-emails/ek-insert-emails.controller.js
src/ui/app/widgets/ek-insert-emails/ek-insert-emails.html

Add blur and space stroke events to finalise invitation email edition

---

src/ui/app/instances/ek-instance-filters/ek-instance-filters.controller.js
src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.controller.js
src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.html
src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.less

Add sub filters for Pod status in instances view

---

build/boxes/ElasticKube/events/start
build/boxes/Pull Request/events/start

@arnaud-elasticbox @albertoarias

Fix devenv default users access

---

src/api/v1/actions/emails.py
src/api/v1/auth.py
src/data/__init__.py
src/ui/app/admin/ek-admin-users/ek-admin-users.html
src/ui/app/admin/ek-admin-users/ek-admin-users.less
src/ui/app/widgets/ek-table/ek-table.less

Fix user table height in admin console

---

src/api/v1/actions/emails.py
src/api/v1/auth.py
src/data/__init__.py
src/ui/app/core/dataflow/users-store.service.js

@EfrenRey @gsanchezu @manolakis

Allow unicode characters in signup form

---

src/api/v1/actions/emails.py
src/api/v1/auth.py
src/data/__init__.py
src/ui/app/admin/ek-admin-settings/ek-admin-settings.controller.js

Fix settings chars lost while typing

---

README.md

Explain where the deployment script comes from

---

src/api/v1/actions/emails.py
src/api/v1/auth.py
src/data/__init__.py
src/ui/app/widgets/ek-ink-ripple/ek-ink-ripple.directive.js
src/ui/app/widgets/ek-ink-ripple/ek-ink-ripple.less

Fix ripple effect on safari and firefox browsers

---

src/api/server.py
src/api/v1/sync/namespaces.py

When http connection is closed properly, reconnect anyway
Add time to log messages
@albertoarias @osanjuan connection can be also closed properly, so we should also reconnect into that case.

Reconnect watch namespaces

---

src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.html
src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.less

Fix instance state filter menu on firefox browser

---

src/api/kube/client.py
src/api/v1/actions/instances.py
src/api/v1/watchers/metadata.py
src/ui/app/instances/ek-instance-details-block/ek-instance-details-block.controller.js
src/ui/app/instances/ek-instance-state-selector/ek-instance-state-selector.controller.js
src/ui/app/instances/ek-instance/ek-instance.html
src/ui/app/widgets/ek-instance-name/ek-instance-name.html

Fixes #90 
Adds ConfigMap, Deployment, ReplicaSet and DaemonSet objects.

Add Deployment ReplicaSet and DaemonSet

---

src/ui/app/login/ek-login/ek-login.less

@EfrenRey 
https://elasticbox.atlassian.net/browse/EBE-3828

[EBE-3828] Fixed login form labels overlapping

---

src/ui/app/admin/ek-admin-settings/ek-admin-settings.controller.js

[EBE-3907] Fix SAML cancel update file

---

build/boxes/Docker Daemon/events/install
src/api/v1/watchers/cursor.py
src/api/v1/watchers/metadata.py
src/data/query.py

Retrieve only first 500 elements for Metrics

---

src/api/v1/auth.py
src/ui/app/login/ek-login/ek-login.controller.js

@manolakis @albertoarias 
Improvements when login with password method:
- Fix the javascript error when a user introduce a bad password
- When a invited user (but not validated) try to login, is redirected to "request an invitation" page
- When a no registered user try to login, is redirected to "request an invitation" page

[EBE-3840] [DONT MERGE] Redirect to validate account or request invite from login

---

build/boxes/ElasticKube/events/install
build/boxes/Pull Request/events/install
build/boxes/Pull Request/events/start
src/Dockerfile-api

The package signature is incorrect
@albertoarias @osanjuan the signature for MongoDB package is incorrect. It happened in the past so I have added a workaround. We can remove it when the signature is fixed.

Install MongoDB shell with --force-yes option

---

build/boxes/Pull Request/events/start
src/api/v1/watchers/__init__.py
src/api/v1/watchers/cursor.py
src/api/v1/watchers/metrics.py

@albertoarias @osanjuan 
This is fixing the metrics filtering and should also fix the tests into the PR

Filter metrics by namespaces on watch

---

src/data/__init__.py

Change default charts repo to point to Kubernetes one
